project:
  type: website
  output-dir: docs

website:
  title: "Russell Luchin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pdfs/RussellLuchin_CV.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

